### PR TITLE
Embedded typings for TypeScript

### PR DESCRIPTION
**Pull request by Borewit**

### CODE REVIEW

**Comment by andrewrk** [comment]
Hey, nice work, however, I don't depend on this module any more for anything, and I don't use type script myself. So I'm not really in a position to merge this or maintain it.

However, if you would like to take ownership of this repo I will happily transfer it to you.

**Comment by Borewit** [comment]
I don't mind to take ownership. Can you transfer the NPM ownership accordingly?

**Comment by andrewrk** [comment]
yes, what is your npm username?

**Comment by andrewrk** [comment]
ok I tried to transfer but you already have a fork with that name.

another idea, i'll just give you npm owner status since this repo is a fork (apparently with no issues enabled) anyway.

**Comment by Borewit** [comment]
Go ahead and try again, I renamed the forked repo.

My NPM username is also "borewit".

**Comment by andrewrk** [comment]
Error message:
> Borewit already has a repository in the pgriess/node-strtok network

**Comment by Borewit** [comment]
_The target account must not have a repository with the same name, or a fork in the same network_. Not sure what the _same network_ means. A bit drastic, but I can delete my repo.

**Comment by Borewit** [comment]
Go for it

**Comment by andrewrk** [comment]
worked

**Comment by Borewit** [comment]
Cheers

**Comment by Borewit** [comment]
TypeScript included in v1.0.2

**Pull request closed without merging**
